language: node_js
node_js:
  - "lts/*"
install:
  - cd app && yarn
script: yarn test
notifications:
  webhooks:
    urls:
      - http://brycejohnson.info/webhook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never

